- package.json
Adding the "browser" field to package.json.
For details, see: https://github.com/defunctzombie/package-browser-field-spec
Useful when one is not using bower to install this package. Atleast webpack seems to pick this up without issue.
Webpack seems to support it - seems like an elegant solution for mixed usage libraries. 
Seems to be a better solution than #27 https://github.com/BigstickCarpet/json-schema-ref-parser/issues/27
> adding support for "browser" field, making inclusion in the browser more robust.

- lib/index.d.ts
- package.json
It doesn't seem like you use TS (at least in your open source work), but it's TS best practice to commit typings directly to the repo they type.
If you would rather not do that, I can do the next best thing and commit these typings to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), the central typings repo for TypeScript.
> add typescript typings

- lib/resolvers/http.js
Hi,
the protocol wasn't present in the HTTP/HTTPS Get request.
Fixes #58 and maybe partial #46.
> Fix missing protocol variable in http.js

- lib/index.d.ts
Current ts definitions specify `canRead` as a required property in options. Fixed it using [`Partial`](https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types) mapped type.
@bcherny, could you plz review
> Fix ts typings for resolve.http and resolve.file

- lib/bundle.js
- test/specs/external-from-internal/definitions/definitions.json
- test/specs/external-from-internal/external-from-internal.bundled.js
- test/specs/external-from-internal/external-from-internal.spec.js
- test/specs/external-from-internal/external-from-internal.yaml
Hey @BigstickCarpet,
ReDoc users found an interesting issue in `json-schema-ref-parser`. This is hard to explain so I will just show an example. If we have two files:
`index.yaml`
```yaml
paths:
$ref: '#/components'
external:
go:
deeper:
$ref: other.yaml#/thing'
components:
test:
$ref: 'other.yaml#/thing'
```
and `other.yaml`:
```yaml
thing:
type: string
```
bundle produced the following output:
```json
{
"paths": {
"$ref": "#/components"
},
"external": {
"go": {
"deeper": {
"$ref": "#/paths/test" // <--- broken ref here
}
}
},
"components": {
"test": {
"type": "string"
}
}
}
```
It actually depends on the deep level of the ref, I believe it has something to sorting order.
I've fixed this in this PR. The fix seems reasonable to me but I'm not sure if this is correct so please check it …
> fix bundle producing schema with corrupted refs in some cases

- lib/pointer.js
- lib/ref.js
- lib/refs.js
- test/specs/refs.spec.js
This is an attempt to fix BigstickCarpet/swagger-parser#76.
I'm a little out of my depth here but as far as I can tell this change should work in all-cases.
> When the parser is unable to resolve a path, give the user supplied path in the error.

- package-lock.json
- package.json
I suspect we don't need `karma-edge-launcher` in production.
> chore: moving karma-edge-launcher to dev dependencies.

- lib/bundle.js
- test/specs/complexOrder/complexOrder.bundled.js
- test/specs/complexOrder/complexOrder.spec.js
- test/specs/complexOrder/definitions/action.json
- test/specs/complexOrder/definitions/def.json
- test/specs/complexOrder/definitions/root.json
- test/specs/complexOrder/definitions/text_assets.json
When there is sufficiently complicated Schema, bundle was overwritting $ref paths. 
I have added 1 extra check in the sort function to fix this. Now if the path from root contains no references to /definitions the paths are ordered alphabetically.
closes #67
> Same file multi definitions

- lib/pointer.js
The following ref was incorrectly resolved by the `Pointer.parse` method:
```js
Pointer.parse("#/paths/~1user/application~1vnd.example%2Bjson/schema")
// returns ["paths", "/user", "application/vnd.example%2Bjson", "schema"]
```
Note that `+` in `application/vnd.example%2Bjson` is not decoded.
The reason is usage of `decodeURI`. Instead, `decodeURIComponent` should be used (tokens are components of the pointer)
> fix refs components decoding

- docs/plugins/resolvers.md
> Add missing `return` in resolvers docs

- .eslintrc.yml
- docs/options.md
- docs/ref-parser.md
- lib/dereference.js
- lib/index.js
- lib/util/meta.js
- test/specs/metadata/external.yaml
- test/specs/metadata/metadata.spec.js
- test/specs/metadata/spec.yaml
Hey @JamesMessinger,
Here is the PoC of `saveOriginalRefs` option for the `dereference` method.
Before I add docs and tests, could you please check it out?
Also, I'm not sure if the same option makes sense for `bundle`. What do you think?
Thanks!
> saveOriginalRefs option for dereference

- lib/index.d.ts
Adjusts the TypeScript typings to allow custom parsers to be specified.
> Allows custom parser declarations

- lib/index.d.ts
`parse` is missing despite being accepted.
It's not exposed in options in docs and neither is `ResolverOptions#read` that's included in typings.
That being said, it feels like a tiny oversight, hence the PR is here.
> Include ParserOptions#parse in TS typings

- README.md
Adding Treeware "conditions of use" test. Also adding basic badge. As requested by Mr Phil Sturgeon.
> Updating to use Treeware

- lib/index.d.ts
- lib/parse.js
- lib/parsers/json.js
- lib/parsers/yaml.js
- lib/util/errors.js
- lib/util/url.js
- lib/util/yaml.js
- package-lock.json
- package.json
- test/specs/callbacks.spec.js
- test/specs/invalid/invalid.spec.js
- test/specs/parsers/parsers.spec.js
Fixes https://github.com/APIDevTools/json-schema-ref-parser/issues/165
Note - I am pretty convinced we should slightly prettify the error messages produced by js-yaml.
Particularly stripping those new lines might beneficial, but I'm fine with keeping them untouched.
I didn't restore YAML tests, not sure if they are truly needed or not - can add them back you find them useful.
Apart from `stringify` method that does not seem to be used anywhere, `parse` is already covered anyway.
> Do not use Stoplight packages

- lib/util/plugins.js
- test/specs/parsers/parsers.spec.js
- test/specs/resolvers/resolvers.spec.js
A small condition making sure each plugin (parser or resolver) actually either called a callback or returned a promise.
Currently, if you use a customs resolvers or parsers and you forget to return the promise or invoke the callback, the promise returned by [run](https://github.com/APIDevTools/json-schema-ref-parser/blob/master/lib/util/plugins.js#L66) function is never resolved leading to a abrupt node process exit.
> Throw when no plugin returned a result

- test/specs/error-source/error-source.spec.js
- test/specs/invalid-pointers/invalid-pointers.js
- test/utils/path.js
Followup PR of https://github.com/APIDevTools/json-schema-ref-parser/pull/167.
Error sources are UNIX-like filepaths, therefore slashes differ.
> Unixify paths in tests

- lib/bundle.js
Related to the indirect refs bundle optimization: https://github.com/APIDevTools/json-schema-ref-parser/pull/62
For large specifications, the current implementation ends up re-crawling a LOT. So much so that for one customer's spec (which is 48k lines, with inline $refs only, no remote ones), it takes around 20s to bundle. 
After a brief investigation, it seems like we might not need to re-crawl if we're just updating the inventoried $ref to be a more direct one?
The tests still pass, but I'm not 100% sure on this and so would appreciate some 👀.
For the specification in question, here's the before and after:
So basically an over 20x increase in performance!
> fix: do not re-crawl unless necessary

- lib/parse.js
- test/specs/parsers/parsers.spec.js
- test/specs/resolvers/resolvers.spec.js
This PR fixes the condition of rejecting empty parsing results.
Currently, when `options.continueOnError` is true and result is empty it will reject.
With this change, it will reject only if `allowEmpty` is false. 
I'm a bit unsure whether this should be still dependent on `continueOnError`.
> Fixes treating empty parsing results

- lib/bundle.js
- lib/dereference.js
- lib/resolve-external.js
This PR addresses the issue outlined in #185: when a schema contains typed arrays or DataViews, this part can safely be skipped during crawling because it cannot contain references.
This PR is marked as a draft because I couldn't figure out how to add tests for this. Initially I wanted to solve this with `chai-spies` such that a spy logs all the paths that the crawler crawled and checks whether the items of typed arrays are excluded from the crawl, but I could not add a spy on the crawler function as it is internal. Any help would be appreciated.
All the existing tests pass, except the HTTP-based ones which fail for a reason unrelated to the PR. Feel free to merge if you think that it is not required to add test cases to cover the changes in this PR.
> Skip typed arrays and DataViews while crawling the schema

- lib/pointer.js
- lib/ref.js
- test/specs/circular-external-direct/circular-external-direct-child.yaml
- test/specs/circular-external-direct/circular-external-direct-root.yaml
- test/specs/circular-external-direct/circular-external-direct.spec.js
- test/specs/circular-external-direct/dereferenced.js
- test/specs/circular-external-direct/parsed.js
- test/specs/circular-external/dereferenced.js
Should fix_ https://github.com/APIDevTools/json-schema-ref-parser/issues/180
Currently json-schema-ref-parser fails to process the document and errors out.
I'm not fully convinced about the fix though, think there might be some slightly nicer way to accomplish the same result?
> Handle direct external circular references

- lib/dereference.js
I had some code break in unexpected ways when ref-parser mutated my schemata (my fault—it doesn’t say it won’t), and deep-froze my inputs to catch it. I then discovered that ref-parser sometimes performs mutations on objects *even when the values do not change*. I suppose frozen schema objects may not be a super common use case, but it seems like a silly thing to break over: the equivalent of `obj[key] = obj[key]` after all does nothing *except* to break if `obj` is frozen.
> Do not mutate objects when values do not change

- lib/dereference.js
fixes #176.
add processedObject list to avoid recursion in already processed tree parts
add dereferencedCache to avoid to  re-treat object already dereferenced
> Performances problems fixes on big files with a lot of references on same big object

- .github/workflows/CI-CD.yaml
- README.md
- package-lock.json
- package.json
Semantic Release is a mixed bag. Some people love it, some people hate it, I try and take a more reasoned approach and use it where it fits, and I think it fits this project. It's great for hands off releasing on projects where folks are pretty damn busy and manual admin is more of a hastle than its worth. This package was a bit out of sync with itself, latest "GitHub Release" was 2.2.0, latest tag was 9.0.6, latest CHANGELOG.md was 9.0.0, and latest NPM was v9.0.7. 
Instead of sending PRs to change the version in `package.json` we can just merge PRs. The [commit format](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) looks like this:
Commit message | Release type
-- | --
fix(pencil): stop graphite breaking when too much pressure applied | Patch …
> Semantic Release

- lib/util/url.js
- test/specs/util/url.spec.js
Given a url `https://example.com/file.yml?foo=bar`, the extension will be parsed as `.yml?foo=bar` and the relevant parsers will miss it.
This PR fixes this issue by stripping the query from the extension.
> add stripQuery method and strip the query from the extension

- lib/dereference.js
In a very large JSON schema (>7MiB), it was found that the overwhelming majority of time was spent on array lookups of the form
`if (arr.indexOf(something) !== -1)`, i.e. existence checks. Changing a few lookup structures to sets and a map, with O(1) lookup time rather than O(N) array lookup, provided a 10x speedup.
Unfortunately, the schema is proprietary and cannot easily be shared.
> Use ES6 collections for lookups in crawl().

- lib/resolve-external.js
- test/specs/circular/circular.spec.js
This will fix a few cases of "Uncaught RangeError: Maximum call stack size exceeded"
Specifically if you have a schema with a circular reference like this:
```javascript
const Node = {
type: 'object',
properties: {
child: {$ref: '#'}
}
}
```
And for whatever reason this gets dereferenced twice:
```javascript
// First call runs fine.
const dereferenced = await $RefParser.dereference(Node)
console.log(dereferenced)
//{
//  type: 'object',
//  properties: { child: [Circular *1] }
//}
// Infinite recursion will occur in resolve-external.js:crawl()
await $RefParser.dereference(dereferenced)
```
And of course this can happen without calling `dereference()` twice. In fact, I can construct a dereferenced schema myself like so:
```javascript
const Node = {
type: 'object',
properties: {
child: null …
```
> stop infinite recursion w/ crawling external refs

- lib/index.d.ts
- lib/pointer.js
- lib/ref.js
- lib/util/errors.js
- test/specs/missing-pointers/external-from-internal.yaml
- test/specs/missing-pointers/missing-pointers.spec.js
Fixes #161.
A small oversight - $Ref.resolve may [return null](https://github.com/APIDevTools/json-schema-ref-parser/blob/master/lib/ref.js#L122) now, so we need to take that into account.
Depends on https://github.com/APIDevTools/json-schema-ref-parser/pull/167 hence leaving it in adraft state.
Last but not least - typed constructors, just in case someone decides to throw these errors in parser or resolver, etc.
> Resolved might be null

- lib/index.d.ts
> fix: add `JSONSchema7` types, `resolve` option index signature & missing `JSONSchema` return type in resolver options `read`

- lib/pointer.js
- lib/ref.js
- lib/resolve-external.js
- test/specs/error-source/error-source.spec.js
Previously, on Windows and Linux (comment here was incorrect) these tests failed if the path contained spaces, because the err.source property used %20 instead of a literal space. This happens because internal URL-encoded path representations are attached directly to the error, instead of the actual path.
While this was commented out as a test error, this is actually a real bug - errors referencing paths all contained unexpectedly encoded strings.
(Pro-tip: store all your code in a local folder with spaces, and it's super easy to catch these issues before they become actual bugs that seriously break things. Easy to do in CI too!)
This change ensures that the path representations are at least decoded correctly before any errors are thrown, so that clear path strings are returned.
It would …
> Fix tests (by fixing error paths generally) when run in paths with spaces

- lib/parsers/yaml.js
- test/specs/date-strings/date-strings.spec.js
- test/specs/date-strings/date-strings.yaml
- test/specs/date-strings/parsed.js
While investigating some `@apidevtools/swagger-parser` quirks I discovered that loading a YAML file that contains a date-like string causes that date to be converted into a `Date` object, causing the API definition to fail validation.
This updates the usage of `js-yaml` to ensure that all YAML content conforms to JSON-compatible types by way of its `schema` option ([docs here](https://github.com/nodeca/js-yaml#load-string---options-)).
> fix: force YAML loading to confirm to JSON-compatible types

- .eslintrc.yml
- .github/workflows/CI-CD.yaml
- .mocharc.yml
- README.md
- lib/resolvers/http.js
- lib/util/url.js
- package-lock.json
- package.json
- test/fixtures/polyfill.js
Fixes #275.
In order to make this lib isomorphic (usable both in the browser and in Node.js), these changes have been made:
- do not use `process` global variable directly
- use `fetch` instead of `http` (Fetch API is available in Node.js as experimental and if not, can be polyfilled easily).
- do not use `url` (use URL API instead).
> feat: make the lib isomorphic

- lib/index.d.ts
The type of onDereference is required, which breaks types in some downstream packages. The code also checks for its existence on L72 of dereference.js so this is fine.
> fix: change type of onDereference to non-required

- .github/workflows/CI-CD.yaml
This PR will configure semantic-release to release a patch version v9.1.2 off the v9 branch, which should revert the breaking change introduced in v9.1.1.
Once this is merged, the release should actually fail with error:
```
EINVALIDNEXTVERSION The release `9.1.1` on branch `v9.1.x` cannot be published as it is out of range.
Based on the releases published on other branches, only versions within the range >=9.1.0 <9.1.1 can be published from branch v9.1.x.
```
The `v9.1.1` tag will need to be moved from the main branch to the `v9.1.x` branch. (This means the git tag will become out of sync with what got released to npm.) Once this tag is moved, rerunning the actions should release `v9.1.2`.
Once this is released, version 9.1.1 will need to be deprecated on npm manually.
> Stage changes to release v9.1.2

- lib/util/convert-path-to-posix.ts
This allows for path-browerify to be used as a polyfill for ui usage.
> fix: lax the windows path conversion if not available

- lib/pointer.ts
- test/specs/internal-root-ref/bundled.ts
- test/specs/internal-root-ref/dereferenced.ts
- test/specs/internal-root-ref/internal-root-ref.spec.ts
- test/specs/internal-root-ref/internal-root-ref.yaml
- test/specs/internal-root-ref/parsed.ts
Previously raised in https://github.com/APIDevTools/json-schema-ref-parser/pull/246 (closed)
Fix for root-level `$ref` properties being interpreted as circular and not resolved.
> fix: resolve root level references

- lib/bundle.ts
- lib/pointer.ts
- lib/ref.ts
- lib/util/plugins.ts
- lib/util/url.ts
- tsconfig.json
Hi, we are using your lib inside a typescript project having the following quite common compilerOptions enabled inside out tsconfig.json.
```
"noImplicitReturns": true,
"noUnusedParameters": true
```
This PR enabled this settings on your project as well because the code issues hiding in your code are letting our tsc fail as well. To enable it I fixed most of the underlying code issues. I added `@ts-ignore` to the `PluginResult` interface because I was too shy to remove the not used generic parameter `O`.
Thank you
> fix: Enable compilerOptions noImplicitReturns and noUnusedParameters to improve type safety

- lib/types/index.ts
Usage of `HeadersInit` requires either a node-fetch dependency or to include DOM in tsconfig libs for consumer projects. It is not exported as a global type in \@types/node v18 or v20. `RequestInit` is:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/aaf94a0a6431f52c46dab26182f1156d79720d29/types/node/v18/globals.d.ts#L341
Define headers in interface `HTTPResolverOptions<>` via `RequestInit['headers']` which will make it possible to depend on this project without node-fetch.
> chore: Improve DOM-less type exports

- docs/options.md
- lib/dereference.ts
- lib/options.ts
- test/specs/circular-extended/circular-extended.spec.ts
- test/specs/circular-external/circular-external.spec.ts
- test/specs/circular/circular.spec.ts
- test/specs/deep-circular/deep-circular.spec.ts
This creates a new `options.dereference.onCircular` hook that will be executed when a circular `$ref` is detected, and similar to `onDereference`, will allow consumers to accumulate a list of circular references within their schemas.
I have written a test for this, and also updated a few test case typos where they were using the legacy `options.$refs` property instead of `options.dereference`.
Closes out https://github.com/APIDevTools/json-schema-ref-parser/issues/358
> feat: creation of a new `onCircular` hook for accumulating circular refs

- lib/pointer.ts
- lib/util/errors.ts
- test/specs/missing-pointers/error-details.yaml
- test/specs/missing-pointers/missing-pointers.spec.ts
Old PR https://github.com/APIDevTools/json-schema-ref-parser/pull/193
> Add more details on missing $ref

- lib/index.ts
This changes the `baseUrl` argument name that's used in a couple spots in the library to more accurately be named `path` instead.
> fix: incorrect argument name

- lib/pointer.ts
- lib/ref.ts
- test/specs/dereference-null-ref/dereference-null-ref.spec.ts
- test/specs/dereference-null-ref/dereference-null-ref.yaml
- test/specs/dereference-null-ref/dereferenced.ts
I've run into a curious issue where the following schema throws a `MissingPointerError` exception:
```yaml
components:
examples:
product:
value:
data:
admission:
$ref: "#/components/examples/product/value/data/pas"
pas: null
```
I'm having a hard time understanding _why_ the `Pointer` class is running this substring lookup for if a token _does_ exist but it's `null`, but because the token we're looking for is the last in the list in this block it never ends up running the `for` loop below this line to look for a substring -- resulting in it falling through to throw a `MissingPointerError`.
https://github.com/APIDevTools/json-schema-ref-parser/blob/5303da99a58089ddaa4ae08f01205ae9df102a67/lib/pointer.ts#L108-L122
I've managed to fix this by doing a secondary "does this token exist and is …
> fix: allow `$ref` pointers to point to a `null` value

- lib/dereference.ts
- test/specs/circular-extensive/circular-extensive.spec.ts
- test/specs/circular-extensive/schema.json
- test/specs/dereference-callback/dereference-callback.spec.ts
We've come across an interesting case with one of our customers OpenAPI definitions where due to the amount of circular references they are using it ends up sending `$RefParser.dereference()` into an infinite loop that has unfortunately been causing us some pain.
The following is a video of running the `dereference.circular=ignore` test in this PR without my eventual fix:
https://github.com/user-attachments/assets/077129bd-997a-40b7-aa57-8129bd7df87f
I've killed the process after 20 seconds but we've seen cases where it can run for almost an hour trying to dereference this circular API definition. In investigating this we've identified a couple issues:
1. When dereferencing this specific schema the event loop gets blocked in the process preventing the `options.timeoutMs` check and …
> fix(BREAKING CHANGE): dereference caching to prevent infinite loops on circular schemas

- lib/dereference.ts
- test/specs/circular-external/circular-external.spec.ts
Apologies for the fast follow here but I uncovered a bug in https://github.com/APIDevTools/json-schema-ref-parser/pull/380 while incorporating v12 into our OpenAPI parser. When dereferencing schemas have external references (eg. `$ref: definitions/child.yaml`) that `$ref` could get saved into the dereference cache as `child.yaml` resulting in the parent schema ending up with an invalid `$ref` pointer that would be `child.yaml`:
This case unfortunately was not caught because the `circular-external` test suite did not have a case for `dereference.circular=ignore`.
I **loathe** the fix I am submitting here but it resolves this, very unique, case and as we both agree in https://github.com/APIDevTools/json-schema-ref-parser/pull/380 that the current dereference caching system needs a …
> fix(dereference): cache poisoning when dereferencing external schemas
